---
- name: Remove old Elasticsearch repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: absent
  ignore_errors: yes

- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - wget

- name: Add Elasticsearch GPG key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
    keyring: /usr/share/keyrings/elasticsearch-keyring.gpg

- name: Add Elasticsearch repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: present
    filename: 'elastic-7.x'

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present

- name: Ensure elasticsearch user and group exist
  user:
    name: elasticsearch
    system: yes
    state: present

# - name: Copy Elasticsearch service file
#   copy:
#     src: elasticsearch.service
#     dest: /etc/systemd/system/elasticsearch.service
#     owner: root
#     group: root
#     mode: '0644'
#   notify:
#     - reload systemd

- name: Enable Elasticsearch service
  systemd:
    name: elasticsearch
    enabled: yes

- name: Wait for 10 seconds before starting the service
  pause:
    seconds: 10

- name: Start Elasticsearch service
  systemd:
    name: elasticsearch
    state: started

- name: Ensure Elasticsearch configuration directory exists
  file:
    path: /etc/elasticsearch
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: '0755'

- name: Copy Elasticsearch configuration file
  copy:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: elasticsearch
    group: elasticsearch
    mode: '0644'
  notify:
    - restart elasticsearch

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart Elasticsearch service
  systemd:
    name: elasticsearch
    state: restarted

- name: Ensure Elasticsearch is running
  systemd:
    name: elasticsearch
    state: started
  retries: 3
  delay: 5
  until: result is success