# my_elasticsearch_role/tasks/main.yml
- name: Add Elasticsearch GPG key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    keyring: /usr/share/keyrings/elasticsearch-keyring.gpg
    state: present
    validate_certs: yes

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Add Elasticsearch APT repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/{{ elasticsearch_version }}/apt stable main"
    filename: elastic-8.x
    state: present

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable Elasticsearch service
  systemd:
    name: elasticsearch
    enabled: yes

- name: Start Elasticsearch service
  systemd:
    name: elasticsearch
    state: started

- name: Check Elasticsearch service status
  command: systemctl status elasticsearch
  register: elasticsearch_status
  ignore_errors: yes

- name: Print Elasticsearch service status
  debug:
    msg: "{{ elasticsearch_status.stdout }}"
